management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true

spring:
  kafka:
    bootstrap-servers: broker:29092
    template:
      default-topic: messageTopic
    consumer:
      group-id: messageId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.chrisbaileydeveloper.messageservice.OrderPlacedEvent
